os:
  - linux
  - osx

language: go

go:
  - tip
  - 1.8
  - 1.7

node_js: "7.5.0"

script:
  - make test-api
  - bash <(curl -s https://codecov.io/bash) -cF api
  - make test-client
  - bash <(curl -s https://codecov.io/bash) -cF client
